### ISSUE TITLE
Close body after timeout

### ISSUE THREAD

**Issue by Javinator9889** [Javinator9889/acexy#4]
Some players are nasty and leave the connection opened even if no data was delivered from AceStream Engine. The middleware is still active, causing the proxy to become unresponsive. Neither the client or the engine are closing the connection, so a restart is needed.

This issue aims to add a configurable field to set a timeout after which, if no data is received, the buffer should be closed.

**Comment by juhacz** [comment]
I don't know if the problem I'm describing is related to this error, but there is a situation when the containser stops responding, I can't watch the video on any device, in the logs I see the latest messages of this type:

```
2024/11/30 22:34:46 INFO Stream done stream="{infohash: fe698c7e71946a794dd8d0e10b14282fbf3f2bdf}"
2024/11/30 22:45:46 INFO Temporary PID pid=6dc9704e-1585-41e9-bac8-e572d453960a stream="{infohash: eed37e83e8b8e2f8bb1e976917e99a3de605ed3f}"
2024/11/30 22:45:47 INFO Started new stream id="{infohash: eed37e83e8b8e2f8bb1e976917e99a3de605ed3f}" clients=0
2024/11/30 22:45:47 WARN Failed to copy response body error="errors (1) when writing to 1 writers\nwrite tcp 192.168.48.2:8080->192.168.100.61:44196: write: broken pipe\n"
2024/11/30 22:45:47 INFO Stream done stream="{infohash: 787bfae1680aeba24aaa5481242cc8d566f0fe30}"
2024/11/30 22:45:49 INFO Temporary PID pid=31022fde-b1ff-4452-a177-9ae29d2430f3 stream="{infohash: 787bfae1680aeba24aaa5481242cc8d566f0fe30}"
2024/11/30 22:45:49 INFO Started new stream id="{infohash: 787bfae1680aeba24aaa5481242cc8d566f0fe30}" clients=0
```

TiViMate connects to the channel endlessly, does not report an error, only the busy circle spins. Only restarting the container helps, then everything starts again. It has happened to me several times.

**Comment by Javinator9889** [comment]
Yes, it's related to that. It happened to me with xTeVe. The problem occurs when you start a stream that has no data but some peers. If you open that stream on AceStream directly, it's stuck in a loop. `acexy` holds the connection open, and causes troubles with newer streams.

By introducing a timeout, I expect those dangling streams to just finish on their own

**Comment by juhacz** [comment]
Great then, I am also waiting for a fix.

**Comment by dceldran** [comment]
Hi @Javinator9889 

I have a question about this, the Acexy proxy has any healthcheck endpoint available? I would like to add a healthy condition in docker with auto restart if acexy becomes unresponsive but when acexy is unresponsive the api stills available so i don't know if i can do what i like. If it is not available, it would be nice having this feature to auto restart container when acexy becomes unresponsive.

Thanks for your job!

**Comment by trananhtuan** [comment]
@dceldran This should be fixed. In the meantime, you can write your own healthcheck as a workaround. If acexy is unresponsive, a request to http://acexy:8080/ace/getstream?id=123 will time out. If it returns HTTP 500 Failed to start stream then the proxy is working fine.

**Comment by Javinator9889** [comment]
The healthcheck is to be addressed in #18

**Comment by trananhtuan** [comment]
First of all, thank you for the hard work.

I'm testing it, and here are my observations:
1. The main process is still blocking, meaning it will not respond to new requests until it times out.
2. acexy does not return an error status in case of an error, so the client keeps trying, and the process repeats all over again.
3. An unhandled exception, as seen here, causes acexy to crash.

```acexy_1  | 2025/02/26 03:33:17 INFO Reusing existing stream="{id: f3a92b47d8c40671e5df2c9148ab3d29f7b5e1cd}" clients=6
acexy_1  | 2025/02/26 03:33:47 ERROR Failed to forward stream error="Get \"http://localhost:6878/ace/r/e82cf5683354d159dbee301bf477f1e44ed7584c/37fcb514e7b6e4b9f2d53e3b58619033\": net/http: timeout awaiting response headers"
acexy_1  | 2025/02/26 03:33:47 http: panic serving 172.18.0.1:34854: close of closed channel
acexy_1  | goroutine 678 [running]:
acexy_1  | net/http.(*conn).serve.func1()
acexy_1  |      /usr/local/go/src/net/http/server.go:1903 +0xbe
acexy_1  | panic({0x6d86a0?, 0x7afc20?})
acexy_1  |      /usr/local/go/src/runtime/panic.go:770 +0x132
acexy_1  | javinator9889/acexy/lib/acexy.(*Acexy).StartStream(0xc00005e1e0, 0xc000068730, {0x7b12e0, 0xc000116700})
acexy_1  |      /app/lib/acexy/acexy.go:176 +0x246
acexy_1  | main.(*Proxy).ServeHTTP(0xc000040050, {0x7b3108, 0xc000116700}, 0xc0001b70e0)
acexy_1  |      /app/proxy.go:84 +0x74e
acexy_1  | net/http.(*ServeMux).ServeHTTP(0x4661d9?, {0x7b3108, 0xc000116700}, 0xc0001b70e0)
acexy_1  |      /usr/local/go/src/net/http/server.go:2688 +0x1ad
acexy_1  | net/http.serverHandler.ServeHTTP({0xc00011f020?}, {0x7b3108?, 0xc000116700?}, 0x6?)
acexy_1  |      /usr/local/go/src/net/http/server.go:3142 +0x8e
acexy_1  | net/http.(*conn).serve(0xc000096bd0, {0x7b37b0, 0xc00006cea0})
acexy_1  |      /usr/local/go/src/net/http/server.go:2044 +0x5e8
acexy_1  | created by net/http.(*Server).Serve in goroutine 1
acexy_1  |      /usr/local/go/src/net/http/server.go:3290 +0x4b4
acexy_1  | 2025/02/26 03:34:17 ERROR Failed to forward stream error="Get \"http://localhost:6878/ace/r/557d64b54659e7c7fbbc456b9ef47617ed2b9631/f8dbe7082592d2f1f048630825171d0c\": net/http: timeout awaiting response headers"
acexy_1  | 2025/02/26 03:34:17 ERROR Failed to start stream error="Get \"http://localhost:6878/ace/r/557d64b54659e7c7fbbc456b9ef47617ed2b9631/f8dbe7082592d2f1f048630825171d0c\": net/http: timeout awaiting response headers"
acexy_1  | 2025/02/26 03:34:47 INFO Reusing existing stream="{id: f3a92b47d8c40671e5df2c9148ab3d29f7b5e1cd}" clients=7
acexy_1  | panic: close of closed channel
acexy_1  |
acexy_1  | goroutine 767 [running]:
acexy_1  | javinator9889/acexy/lib/acexy.(*Acexy).StartStream.func1()
acexy_1  |      /app/lib/acexy/acexy.go:200 +0x288
acexy_1  | created by javinator9889/acexy/lib/acexy.(*Acexy).StartStream in goroutine 631
acexy_1  |      /app/lib/acexy/acexy.go:188 +0x3df
acexy_1  | 2025/02/26 03:34:49 INFO Starting server addr=:8080
acexy_1  | 2025/02/26 03:34:49 INFO Temporary PID pid=e6d8091b-6e89-4df8-8b41-433e52b4d464 stream="{id: b7e234f6a5bc98d3c4012ef5678a9dc45237abcf}"
acexy_1  | 2025/02/26 03:34:49 WARN Error getting stream error="Get \"http://localhost:6878/ace/getstream?format=json&id=b7e234f6a5bc98d3c4012ef5678a9dc45237abcf&pid=e6d8091b-6e89-4df8-8b41-433e52b4d464\": dial tcp [::1]:6878: connect: connection refused"```

**Comment by Javinator9889** [comment]
Hello,

Thanks for the report! First, try with the latest main branch, please. I have addressed a similar issue to that in a later commit

Let me know if it persists, and create a bug report if so

**Comment by trananhtuan** [comment]
That was the main branch.

**Comment by Javinator9889** [comment]
OK, I'll take a look at it in a while 

Thanks!

**Comment by Javinator9889** [comment]
@trananhtuan I'm working on this, but I cannot reproduce it with my current setup. Can you please share the AceStream ID you used to trigger the issue?

**Comment by juhacz** [comment]
@Javinator9889: After quick tests in the latest released version there is still something wrong, after selecting a stream, when it is not possible to play it, the proxy stops responding. here is the log from the container:
```

025/02/28 18:24:51 INFO Client closed connection stream="{infohash: 787bfae1680aeba24aaa5481242cc8d566f0fe30}"
2025/02/28 18:24:51 INFO Temporary PID pid=1ad1fc5c-ee17-49cb-a470-c8efe426d9e9 stream="{infohash: 8bd365dd6c2486d8f11f7850f2cf8107c0563f1b}"
2025/02/28 18:24:51 INFO Started new stream id="{infohash: 8bd365dd6c2486d8f11f7850f2cf8107c0563f1b}" clients=0
2025/02/28 18:27:39 INFO Temporary PID pid=8fc98f3a-8606-4d6f-a8dc-a68fd6cb2681 stream="{infohash: 2ebd92b91c253702637e1c254b1c68c22c85279f}"
2025/02/28 18:27:40 INFO Started new stream id="{infohash: 2ebd92b91c253702637e1c254b1c68c22c85279f}" clients=0
2025/02/28 18:33:39 INFO Stream done stream="{infohash: 2ebd92b91c253702637e1c254b1c68c22c85279f}"
2025/02/28 18:33:39 INFO Client closed connection stream="{infohash: 2ebd92b91c253702637e1c254b1c68c22c85279f}"
2025/02/28 18:33:39 INFO Temporary PID pid=1789c90e-9853-42f3-aa55-2d18506f55cb stream="{infohash: 3cb105050659f11d0dfd0e344598f7fc91e01adc}"
2025-02-28 18:33:40,007|Thread-359 (process_request_thread)|acestream.LiveDownloadImpl.3cb105050659f11d0dfd0e344598f7fc91e01adc|update_manifest: got http error: code=500 msg=<urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>
2025/02/28 18:34:41 WARN Failed to copy response body error="errors (1) when writing to 1 writers\nwrite tcp 192.168.64.2:8080->192.168.100.4:4261: write: broken pipe\n"
2025/02/28 18:34:41 INFO Stream done stream="{infohash: 8bd365dd6c2486d8f11f7850f2cf8107c0563f1b}"
2025/02/28 18:35:40 WARN Error in stream response error="failed to get manifest"
2025/02/28 18:35:40 ERROR Error getting stream middleware error="failed to get manifest"
2025/02/28 18:35:40 ERROR Failed to start stream error="failed to get manifest"
2025/02/28 18:35:40 INFO Temporary PID pid=71a2d109-ca70-4ac9-b3eb-c06fd15b83db stream="{infohash: 3cb105050659f11d0dfd0e344598f7fc91e01adc}"
2025-02-28 18:35:40,139|Thread-359 (process_request_thread)|acestream.LiveDownloadImpl.3cb105050659f11d0dfd0e344598f7fc91e01adc|update_manifest: got http error: code=500 msg=<urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>
2025/02/28 18:37:40 WARN Error in stream response error="failed to get manifest"
2025/02/28 18:37:40 ERROR Error getting stream middleware error="failed to get manifest"
2025/02/28 18:37:40 ERROR Failed to start stream error="failed to get manifest"
2025/02/28 18:37:40 INFO Temporary PID pid=4010ab73-994c-4067-945e-acddded02245 stream="{infohash: 3cb105050659f11d0dfd0e344598f7fc91e01adc}"
2025-02-28 18:37:40,308|Thread-359 (process_request_thread)|acestream.LiveDownloadImpl.3cb105050659f11d0dfd0e344598f7fc91e01adc|update_manifest: got http error: code=500 msg=<urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>

```

**Comment by Javinator9889** [comment]
> @Javinator9889: After quick tests in the latest released version there is still something wrong, after selecting a stream, when it is not possible to play it, the proxy stops responding. here is the log from the container:
> ```
> 
> 025/02/28 18:24:51 INFO Client closed connection stream="{infohash: 787bfae1680aeba24aaa5481242cc8d566f0fe30}"
> 2025/02/28 18:24:51 INFO Temporary PID pid=1ad1fc5c-ee17-49cb-a470-c8efe426d9e9 stream="{infohash: 8bd365dd6c2486d8f11f7850f2cf8107c0563f1b}"
> 2025/02/28 18:24:51 INFO Started new stream id="{infohash: 8bd365dd6c2486d8f11f7850f2cf8107c0563f1b}" clients=0
> 2025/02/28 18:27:39 INFO Temporary PID pid=8fc98f3a-8606-4d6f-a8dc-a68fd6cb2681 stream="{infohash: 2ebd92b91c253702637e1c254b1c68c22c85279f}"
> 2025/02/28 18:27:40 INFO Started new stream id="{infohash: 2ebd92b91c253702637e1c254b1c68c22c85279f}" clients=0
> 2025/02/28 18:33:39 INFO Stream done stream="{infohash: 2ebd92b91c253702637e1c254b1c68c22c85279f}"
> 2025/02/28 18:33:39 INFO Client closed connection stream="{infohash: 2ebd92b91c253702637e1c254b1c68c22c85279f}"
> 2025/02/28 18:33:39 INFO Temporary PID pid=1789c90e-9853-42f3-aa55-2d18506f55cb stream="{infohash: 3cb105050659f11d0dfd0e344598f7fc91e01adc}"
> 2025-02-28 18:33:40,007|Thread-359 (process_request_thread)|acestream.LiveDownloadImpl.3cb105050659f11d0dfd0e344598f7fc91e01adc|update_manifest: got http error: code=500 msg=<urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>
> 2025/02/28 18:34:41 WARN Failed to copy response body error="errors (1) when writing to 1 writers\nwrite tcp 192.168.64.2:8080->192.168.100.4:4261: write: broken pipe\n"
> 2025/02/28 18:34:41 INFO Stream done stream="{infohash: 8bd365dd6c2486d8f11f7850f2cf8107c0563f1b}"
> 2025/02/28 18:35:40 WARN Error in stream response error="failed to get manifest"
> 2025/02/28 18:35:40 ERROR Error getting stream middleware error="failed to get manifest"
> 2025/02/28 18:35:40 ERROR Failed to start stream error="failed to get manifest"
> 2025/02/28 18:35:40 INFO Temporary PID pid=71a2d109-ca70-4ac9-b3eb-c06fd15b83db stream="{infohash: 3cb105050659f11d0dfd0e344598f7fc91e01adc}"
> 2025-02-28 18:35:40,139|Thread-359 (process_request_thread)|acestream.LiveDownloadImpl.3cb105050659f11d0dfd0e344598f7fc91e01adc|update_manifest: got http error: code=500 msg=<urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>
> 2025/02/28 18:37:40 WARN Error in stream response error="failed to get manifest"
> 2025/02/28 18:37:40 ERROR Error getting stream middleware error="failed to get manifest"
> 2025/02/28 18:37:40 ERROR Failed to start stream error="failed to get manifest"
> 2025/02/28 18:37:40 INFO Temporary PID pid=4010ab73-994c-4067-945e-acddded02245 stream="{infohash: 3cb105050659f11d0dfd0e344598f7fc91e01adc}"
> 2025-02-28 18:37:40,308|Thread-359 (process_request_thread)|acestream.LiveDownloadImpl.3cb105050659f11d0dfd0e344598f7fc91e01adc|update_manifest: got http error: code=500 msg=<urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>
> 
> ```

Awesome!! Thanks for testing it, with that information I think I can easily fix this :)

I'll ping you once it's solved

**Comment by trananhtuan** [comment]
> * The main process is still blocking, meaning it will not respond to new requests until it times out.
> 
> * ~~acexy does not return an error status in case of an error, so the client keeps trying, and the process repeats all over again.~~
> 
> * ~~An unhandled exception, as seen here, causes acexy to crash.~~


Again, thanks for the good work. I see you have been able to reintroduce the issue. My testing on the main branch shows that ACEXY no longer crashes and the timed-out streams are no longer repeated. It still doesn't return an error to the player, but that's not critical.

Regarding the first point, the addition of ACEXY_NO_RESPONSE_TIMEOUT allows for adjusting the timeout. However, because the code is not asynchronous, ACEXY will not respond to new requests until it times out.

Additionally, the default ACEXY_NO_RESPONSE_TIMEOUT=1s is too short. In my testing, no stream is playable with this default setting.

**Comment by Javinator9889** [comment]
Thanks for the reports @trananhtuan 

Some things to clarify:

- Acexy **is asynchronous**, but some critical processes and steps are synchronous. The issues you are facing happen because the intermediate AceStream middleware is not responding, so Acexy has no means to start the stream. From Acexy POV, the stream is loading but not ready yet. That step is critical and therefore synchronous, and won't be changed.
- The `ACEXY_NO_RESPONSE_TIMEOUT` should be long enough for the middleware to grab stream information. If it's taking more than 1s, you have a super slow Internet connection. Feel free to adjust it on your end to a higher value that fits you.
- Acexy **does return** an error code to the player. However, most of the players just retry on error. That's the behavior you're seeing, it has nothing to do with Acexy. If you still think the proxy is not returning an error, please grab the network packets, and the report of tools like cURL, and fill a bug issue.

Again, thanks a lot for your support and help. I'll try to fix all the remaining known problems to release Acexy throughout this weekend.
